# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  # vagrant plugin install vagrant-libvirt 
  config.vagrant.plugins = ["vagrant-libvirt"] 
  config.vm.provider :libvirt do |l|
    l.memory = 1024
  end  


  config.vm.define "debian1" do |debian|
    debian.vm.hostname = "debian1"
    debian.vm.network :private_network, ip: "192.168.56.10"
  end 
 
  config.vm.define "debian2" do |debian|
    debian.vm.hostname = "debian2"
    debian.vm.network :private_network, ip: "192.168.56.20"
  end 
 
 config.vm.define "debian3" do |debian|
    debian.vm.hostname = "debian3"
    debian.vm.network :private_network, ip: "192.168.56.30"
  end 
end
