# -*- mode: ruby -*-
# vi: set ft=rbuy :
Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/8"
  config.vagrant.plugins = ["vagrant-libvirt"]  
  config.vm.provider :libvirt do |l|
    l.memory = 1024
  end

  config.vm.define "app1" do |app|
    app.vm.hostname = "app1"
    app.vm.network :private_network, ip: "192.168.60.4"
    app.vm.network :forwarded_port, id: 'http', guest: 80, host: 8080
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
